import { CardinalModelEntity, CardinalScopeOption } from '../../../entities/CardinalModelEntity';
import { CardinalModel } from '../../Models';

export enum PowerSyncInstanceModelAction {
  READ = 'read',
  CREATE = 'create',
  DELETE = 'delete',
  UPDATE = 'update',
  VIEW_LOGS = 'view-logs'
}

export class PowerSyncInstanceModel extends CardinalModelEntity<PowerSyncInstanceModelAction> {
  constructor() {
    super({
      model: CardinalModel.POWERSYNC_INSTANCE,
      label: 'PowerSync Instance',
      description: 'Represents a PowerSync instance.'
    });

    this.addAction({
      action: PowerSyncInstanceModelAction.READ,
      label: 'Read',
      description: 'Read a PowerSync instance.'
    });

    this.addAction({
      action: PowerSyncInstanceModelAction.CREATE,
      label: 'Create',
      description: 'Create a PowerSync instance.'
    });

    this.addAction({
      action: PowerSyncInstanceModelAction.DELETE,
      label: 'Delete',
      description: 'Delete a PowerSync instance.'
    });

    this.addAction({
      action: PowerSyncInstanceModelAction.UPDATE,
      label: 'Update',
      description: 'Update a PowerSync instance.'
    });

    this.addAction({
      action: PowerSyncInstanceModelAction.VIEW_LOGS,
      label: 'View Logs',
      description: 'View logs generated by a PowerSync instance.'
    });

    this.addParent(CardinalModel.APP);
  }
}
